'use strict';
function reportList(a, limit=200) {
  const reports=[...(a.automation_history||[])].reverse().slice(0,limit);
  if(!reports.length)return '<p class="settings-copy">No automation reports for this asset. Manual editing works independently.</p>';
  return reports.map(r=>`<div class="report-card"><div class="report-heading"><strong>${esc(r.source)}</strong><span class="badge">${r.mode==='apply'?'Auto-applied':r.decision?esc(title(r.decision)):'Needs review'}</span></div><p class="settings-copy">${esc(new Date(r.at).toLocaleString())}</p><dl class="report-values">${Object.entries(r.changes).map(([key,value])=>`<dt>${esc(title(key.replace('details.','')))}</dt><dd>${esc(value)}</dd>`).join('')}</dl>${r.mode==='report'&&!r.reviewed_at?button('Review observation','review-report',a.id+'|'+r.id,'btn small'):''}</div>`).join('');
}
function automationDetail(a){return `<section class="panel">${panelHead('Automation observations','Latest report per connection plus adverse observations (up to 50 distinct conditions). Repeated conditions replace earlier reports.','<a class="text-link" href="#automations">Manage →</a>')}<div class="detail-body">${reportList(a)}</div></section>`;}
function automations(){
 const clients=state.automation_clients||[], pending=[];
 for(const a of state.assets){const latest=Object.values(Object.fromEntries((a.automation_history||[]).map(r=>[r.client_id,r])));for(const r of latest)if(r.mode==='report'&&!r.reviewed_at)pending.push([a,r]);}
 return heading('MANUAL FIRST. AUTOMATION WHEN USEFUL.','Automation connections','Let scripts report what they find. Choose whether they suggest updates or apply them.',button('＋ Connect an automation','new-automation','','btn primary'))+
 `<div class="welcome"><div><h2>You stay in control.</h2><p>Each key works with one asset and only the fields you select. Scripts cannot edit purposes, notes, recovery instructions, or manual verification. Closing the desktop window keeps the API available in the system tray.</p></div></div>`+
 `<div class="stats"><div class="stat"><span class="stat-label">Connections</span><strong>${clients.length}</strong><small>Explicitly scoped automation keys</small></div><div class="stat"><span class="stat-label">Enabled</span><strong>${clients.filter(c=>c.enabled).length}</strong><small>Paused keys cannot report</small></div><div class="stat"><span class="stat-label">Direct updates</span><strong>${clients.filter(c=>c.enabled&&c.mode==='apply').length}</strong><small>Only approved fields can change</small></div><div class="stat amber"><span class="stat-label">Awaiting review</span><strong>${pending.length}</strong><small>Latest observations per connection</small></div></div>`+
 `<section class="panel">${panelHead('Connected automations','Secrets are shown once. Only their hashes are stored; exports never include keys.')}${clients.length?`<div class="table-wrap"><table><thead><tr><th>Automation / asset</th><th>Mode</th><th>Allowed fields</th><th>Last report</th><th>Controls</th></tr></thead><tbody>${clients.map(c=>`<tr><td><strong>${esc(c.name)}</strong><small>${esc(asset(c.asset_id)?.name||'Asset removed')}</small></td><td>${badge(c.enabled?'ACTIVE':'PAUSED')}<small>${c.mode==='apply'?'Apply allowed fields':'Report for review'}</small></td><td>${c.fields.map(f=>esc(f)).join('<br>')}</td><td>${day(c.last_seen)}</td><td><div class="actions">${button(c.enabled?'Pause':'Resume','toggle-automation',c.id,'btn small')}${button(c.mode==='apply'?'Require review':'Allow updates','mode-automation',c.id,'btn small')}${button('Revoke','revoke-automation',c.id,'btn small danger')}</div></td></tr>`).join('')}</tbody></table></div>`:empty('No automations connected','Add an asset first, then create a scoped key. Your inventory does not depend on automation.')}</section>`+
 `<div class="settings-grid"><section class="panel">${panelHead('Observations awaiting review','Review the latest values before accepting them.')}${pending.length?pending.map(([a,r])=>`<div class="maintenance-card"><div><strong>${esc(a.name)}</strong><p>${esc(r.source)} · ${esc(new Date(r.at).toLocaleString())}</p><p>${Object.keys(r.changes).map(esc).join(', ')}</p></div>${button('Review','review-report',a.id+'|'+r.id,'btn small')}</div>`).join(''):empty('No observations waiting','Report-only connections will leave observations here.')}</section><section class="panel">${panelHead('Connect your own scripts','Local endpoint · no scheduler dependency')}<div class="detail-body"><p class="settings-copy">Send a JSON POST to <code>${esc(location.origin)}/api/automation/report</code> with <code>Authorization: Bearer YOUR_KEY</code>.</p><pre class="code-example">${esc(JSON.stringify({event_id:'unique-run-id',changes:{last_heartbeat:'2026-09-24T14:00:00Z',status:'ONLINE'}},null,2))}</pre><p class="settings-copy">Only send fields permitted by your key. Ready-to-use PowerShell and Python examples are in the project’s <code>examples/</code> folder. They report once; no scheduled jobs have been installed.</p><p class="settings-copy">If this app is unavailable, your scripts should continue their primary work and retry reporting later. Existing manual controls always remain available.</p></div></section></div>`;
}
function automationForm(){
 if(!state.assets.length){notify('Add the asset you want to report on first.');return;}
 const initial=state.assets[0];
 function fields(id){return (state.automation_fields[id]||[]).map(key=>`<label class="checkbox"><input name="allowed" type="checkbox" value="${esc(key)}" ${key==='last_heartbeat'?'checked':''}>${esc(key)}</label>`).join('');}
 openModal('Connect an automation',`<div class="form-grid">${input('name','Automation name','','text','For example, workstation heartbeat or nightly backup.')}${select('asset_id','Asset it may update',state.assets.map(a=>[a.id,a.name]),initial.id)}${select('mode','How reports are handled',[['report','Review observations first'],['apply','Apply allowed fields automatically']],'report')}</div><div class="form-section"><h3>Allowed fields</h3><p class="settings-copy">Grant only the fields this script needs. Manual verification and restore testing are never available to automation.</p><div class="automation-fields" id="automation-fields">${fields(initial.id)}</div></div>`,async form=>{
   const result=await api('automations/create',{name:form.get('name'),asset_id:form.get('asset_id'),mode:form.get('mode'),fields:form.getAll('allowed')});
   await changed('Automation connection created');
   // Show the secret without putting it in app state, persistent storage, or logs.
   $('#dialog').innerHTML=`<div class="dialog-head"><h2 id="dialog-title">Save this automation key</h2>${button('×','close','','text-link')}</div><div class="dialog-body"><p class="settings-copy">This is the only time the key is shown. Save it in your credential manager or script environment. It is scoped to ${esc(asset(result.client.asset_id)?.name)}.</p><label class="field">Automation key<input readonly value="${esc(result.secret)}" autocomplete="off" spellcheck="false"></label><p class="settings-copy">Environment variable: <code>REBORN_AUTOMATION_KEY</code><br>Endpoint: <code>${esc(location.origin)}/api/automation/report</code></p></div><div class="dialog-foot">${button('I saved the key','close','','btn primary')}</div>`;
   return {keepOpen:true};
 },'Create scoped key');
 $('[name="asset_id"]',$('#dialog')).addEventListener('change',event=>{$('#automation-fields').innerHTML=fields(event.target.value);});
}
Object.assign(actions,{
 'new-automation':automationForm,
 'toggle-automation':async id=>{const c=state.automation_clients.find(c=>c.id===id);await api('automations/update',{id,enabled:!c.enabled,mode:c.mode});await changed(c.enabled?'Automation paused':'Automation resumed');},
 'mode-automation':id=>{const c=state.automation_clients.find(c=>c.id===id);const mode=c.mode==='apply'?'report':'apply';confirmAction(mode==='apply'?'Allow automatic updates?':'Require review first?',mode==='apply'?`${c.name} will be able to overwrite these fields on ${asset(c.asset_id)?.name}: ${c.fields.join(', ')}. Every update is recorded. Manual verification remains unchanged.`:'Future reports will wait for review without changing asset fields.',async()=>{await api('automations/update',{id,enabled:c.enabled,mode});await changed('Automation mode updated');},mode==='apply'?'Allow updates':'Require review');},
 'revoke-automation':id=>confirmAction('Revoke automation key?','This script will no longer be able to report. Its observations remain in the asset history. Create a new key if you want to reconnect it later.',async()=>{await api('automations/revoke',{id});await changed('Automation key revoked');},'Revoke key'),
 'review-report':value=>{const [id,reportId]=value.split('|'),a=asset(id),r=a.automation_history.find(r=>r.id===reportId);const current=key=>key.startsWith('details.')?a.details[key.slice(8)]||'':a[key];openModal('Review automation observation',`<p class="settings-copy">${esc(r.source)} reported these values for <strong>${esc(a.name)}</strong> at ${esc(new Date(r.at).toLocaleString())}. Accepting replaces the listed current values. It does not count as manual verification.</p><div class="table-wrap"><table><thead><tr><th>Field</th><th>Current value</th><th>Reported value</th></tr></thead><tbody>${Object.entries(r.changes).map(([key,value])=>`<tr><td>${esc(key)}</td><td>${esc(current(key))}</td><td>${esc(value)}</td></tr>`).join('')}</tbody></table></div><div class="form-section">${select('decision','Decision',[['accepted','Accept these values'],['dismissed','Dismiss and keep my values']],'accepted')}</div>`,async form=>{await api('automations/review',{asset_id:id,report_id:reportId,revision:a.revision||0,decision:form.get('decision')});await changed('Observation reviewed');},'Save decision');}
});
setInterval(async()=>{if(!state||document.hidden||$('#dialog').open||document.querySelector('#main details[open]')||current==='settings'||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;try{await load();render();}catch{}},15000);
